name: F1 Data Pipeline

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Deploy to Databricks
        run: databricks bundle deploy
        env:
          DATABRICKS_HOST: https://dbc-97897a73-b66b.cloud.databricks.com
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}